USE master
GO

CREATE DATABASE ANTA
GO

USE ANTA
GO

CREATE TABLE DANHMUC (
    MaDM VARCHAR(30) NOT NULL PRIMARY KEY,
    TenDM NVARCHAR(50) NOT NULL,
	MaDMCha VARCHAR(30) NULL,
    CONSTRAINT fk_dm_madmcha FOREIGN KEY (MaDMCha) REFERENCES DANHMUC(MaDM)
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR(30) NOT NULL PRIMARY KEY,
    TenSP NVARCHAR(50) NOT NULL,
    DonGia MONEY NOT NULL,
    SoLuong INT NOT NULL,
    MoTa NVARCHAR(2000) NOT NULL,
    KichThuoc NVARCHAR(10) NOT NULL,
	MauSac NVARCHAR(30) NOT NULL,
    HinhAnh NVARCHAR(100) NOT NULL,
    ThuongHieu NVARCHAR(100) NOT NULL,
    LoaiSanPham NVARCHAR(100) NOT NULL,
	MaDM VARCHAR(30) NOT NULL,
    CONSTRAINT fk_sp_madm FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM)  
);

CREATE TABLE KHUYENMAI (
    MaKM VARCHAR(30) NOT NULL PRIMARY KEY,
    TenCT NVARCHAR(50) NOT NULL,
    TiLe FLOAT NOT NULL,
    Gia MONEY NOT NULL,
    MoTa NVARCHAR(500) NOT NULL,
    ThoiGianBD DATETIME NOT NULL,
    ThoiGianKT DATETIME NOT NULL
);

CREATE TABLE CHITIETKHUYENMAI (
    MaSP VARCHAR(30) NOT NULL,
    MaKM VARCHAR(30) NOT NULL,
	SoLuong INT NOT NULL,
	GiaKhuyenMai MONEY,
    CONSTRAINT pk_chi_tiet_km PRIMARY KEY (MaSP, MaKM),
    CONSTRAINT fk_ctkm_masp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT fk_ctkm_makm FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);

CREATE TABLE PHIEUGIAMGIA (
    MaPGG VARCHAR(30) NOT NULL PRIMARY KEY,
    TenPGG NVARCHAR(50) NOT NULL,
    TiLe FLOAT NOT NULL,
    ThoiGianBD DATETIME NOT NULL,
    ThoiGianKT DATETIME NOT NULL,
    MoTa NVARCHAR(500) NOT NULL
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(30) NOT NULL PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    Tuoi INT NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL
);

CREATE TABLE GIOHANG (
    MaGH VARCHAR(30) NOT NULL PRIMARY KEY,
    MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_gio_hang_makh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CHITIETGIOHANG (
    MaGH VARCHAR(30) NOT NULL,
    MaSP VARCHAR(30) NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT pk_ctgh PRIMARY KEY (MaGH, MaSP),
	CONSTRAINT fk_ctgh_magh FOREIGN KEY (MaGH) REFERENCES GIOHANG(MaGH),
    CONSTRAINT fk_ctgh_masp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE WISHLIST (
    MaWL VARCHAR(30) NOT NULL PRIMARY KEY,
    MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_wl_makh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CHITIETWISHLIST (
    MaWL VARCHAR(30) NOT NULL,
    MaSP VARCHAR(30) NOT NULL,
	DaThemVaoGioHang BIT NOT NULL,
	MucGiaMongMuon MONEY NOT NULL,
    CONSTRAINT pk_ctwl PRIMARY KEY (MaWL, MaSP),
	CONSTRAINT fk_ctwl_mawl FOREIGN KEY (MaWL) REFERENCES WISHLIST(MaWL),
    CONSTRAINT fk_ctwl_masp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE CUAHANG (
    MaCH VARCHAR(30) NOT NULL PRIMARY KEY,
    TenCH NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    MoTa NVARCHAR(1000) NOT NULL
);

CREATE TABLE DONHANG (
    MaDH VARCHAR(30) NOT NULL PRIMARY KEY,
    NgayDat DATETIME NOT NULL,
    HoTenNguoiNhan NVARCHAR(50) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    GhiChu NVARCHAR(200),
    PTThanhToan NVARCHAR(50) NOT NULL,
    HTVanChuyen NVARCHAR(50) NOT NULL,
	TrangThai NVARCHAR(100) NOT NULL,
    MaPGG VARCHAR(30) NOT NULL,
    MaCH VARCHAR(30) NOT NULL,
    MaGH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_dh_mapgg FOREIGN KEY (MaPGG) REFERENCES PHIEUGIAMGIA(MaPGG),
	CONSTRAINT fk_dh_mach FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH),
	CONSTRAINT fk_dh_magh FOREIGN KEY (MaGH) REFERENCES GIOHANG(MaGH)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(30) NOT NULL PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    Tuoi INT NOT NULL,
    GioiTinh NVARCHAR(1) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    MaCH VARCHAR(30) NOT NULL,
	MaQL VARCHAR(30) NOT NULL,
	CONSTRAINT fk_nv_maql FOREIGN KEY (MaQL) REFERENCES NHANVIEN(MaNV),
	CONSTRAINT fk_nv_mach FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH)
);


CREATE TABLE TINTUC (
    MaTinTuc VARCHAR(30) NOT NULL PRIMARY KEY,
    TieuDe NVARCHAR(200) NOT NULL,
    NoiDung NVARCHAR(500) NOT NULL,
    NgayDang DATETIME NOT NULL,
    HinhAnh NVARCHAR(100),
    MaNV VARCHAR(30) NOT NULL,
	CONSTRAINT fk_tt_manv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE DANHGIA(
    MaDG VARCHAR(30) NOT NULL PRIMARY KEY,
    Diem FLOAT NOT NULL,
    NoiDung NVARCHAR(200),
    HinhAnh NVARCHAR(100),
    MaSP VARCHAR(30) NOT NULL,
	MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_dg_masp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
	CONSTRAINT fk_dg_makh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);
GO