USE master
GO

CREATE DATABASE ANTA
GO

USE ANTA
GO

CREATE TABLE DANH_MUC (
    MaDM VARCHAR(30) NOT NULL PRIMARY KEY,
    TenDM NVARCHAR(50) NOT NULL,
	MaDMCha VARCHAR(30) NULL,
    CONSTRAINT fk_dm_madmcha FOREIGN KEY (MaDMCha) REFERENCES DANH_MUC(MaDM)
);

CREATE TABLE SAN_PHAM (
    MaSP VARCHAR(30) NOT NULL PRIMARY KEY,
    TenSP NVARCHAR(50) NOT NULL,
    DonGia MONEY NOT NULL,
    SoLuong INT NOT NULL,
    MoTa NVARCHAR(2000) NOT NULL,
    KichThuoc NVARCHAR(10) NOT NULL,
	MauSac NVARCHAR(30) NOT NULL,
    HinhAnh NVARCHAR(100) NOT NULL,
    ThuongHieu NVARCHAR(100) NOT NULL,
    LoaiSanPham NVARCHAR(100) NOT NULL,
	MaDM VARCHAR(30) NOT NULL,
    CONSTRAINT fk_sp_madm FOREIGN KEY (MaDM) REFERENCES DANH_MUC(MaDM)  
);

CREATE TABLE KHUYEN_MAI (
    MaKM VARCHAR(30) NOT NULL PRIMARY KEY,
    TenCT NVARCHAR(50) NOT NULL,
    TiLe FLOAT NOT NULL,
    Gia MONEY NOT NULL,
    MoTa NVARCHAR(500) NOT NULL,
    NgayBD DATETIME NOT NULL,
    NgayKT DATETIME NOT NULL
);

CREATE TABLE CHI_TIET_KHUYEN_MAI (
    MaSP VARCHAR(30) NOT NULL,
    MaKM VARCHAR(30) NOT NULL,
	SoLuong INT NOT NULL,
	GiaKhuyenMai MONEY,
    CONSTRAINT pk_chi_tiet_km PRIMARY KEY (MaSP, MaKM),
    CONSTRAINT fk_ctkm_masp FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP),
    CONSTRAINT fk_ctkm_makm FOREIGN KEY (MAKM) REFERENCES KHUYEN_MAI(MAKM)
);

CREATE TABLE PHIEU_GIAM_GIA (
    MaPGG VARCHAR(30) NOT NULL PRIMARY KEY,
    TenPGG NVARCHAR(50) NOT NULL,
    TiLe FLOAT NOT NULL,
    NgayBD DATETIME NOT NULL,
    NgayKT DATETIME NOT NULL,
    MoTa NVARCHAR(500) NOT NULL
);

CREATE TABLE KHACH_HANG (
    MaKH VARCHAR(30) NOT NULL PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    Tuoi INT NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL
);

CREATE TABLE GIO_HANG (
    MaGH VARCHAR(30) NOT NULL PRIMARY KEY,
    MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_gio_hang_makh FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

CREATE TABLE CHI_TIET_GIO_HANG (
    MaGH VARCHAR(30) NOT NULL,
    MaSP VARCHAR(30) NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT pk_ctgh PRIMARY KEY (MaGH, MaSP),
	CONSTRAINT fk_ctgh_magh FOREIGN KEY (MaGH) REFERENCES GIO_HANG(MaGH),
    CONSTRAINT fk_ctgh_masp FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE WISHLIST (
    MaWL VARCHAR(30) NOT NULL PRIMARY KEY,
    MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_wl_makh FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

CREATE TABLE CHI_TIET_WISHLIST (
    MaWL VARCHAR(30) NOT NULL,
    MaSP VARCHAR(30) NOT NULL,
	DaThemVaoGioHang BIT NOT NULL,
	MucGiaMongMuon MONEY NOT NULL,
    CONSTRAINT pk_ctwl PRIMARY KEY (MaWL, MaSP),
	CONSTRAINT fk_ctwl_mawl FOREIGN KEY (MaWL) REFERENCES WISHLIST(MaWL),
    CONSTRAINT fk_ctwl_masp FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE CUA_HANG (
    MaCH VARCHAR(30) NOT NULL PRIMARY KEY,
    TenCH NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    MoTa NVARCHAR(1000) NOT NULL
);

CREATE TABLE DON_HANG (
    MaDH VARCHAR(30) NOT NULL PRIMARY KEY,
    NgayDat DATETIME NOT NULL,
    HoTenNguoiNhan NVARCHAR(50) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    GhiChu NVARCHAR(200),
    PTThanhToan NVARCHAR(50) NOT NULL,
    HTVanChuyen NVARCHAR(50) NOT NULL,
    MaPGG VARCHAR(30) NOT NULL,
    MaCH VARCHAR(30) NOT NULL,
    MaGH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_dh_mapgg FOREIGN KEY (MaPGG) REFERENCES PHIEU_GIAM_GIA(MaPGG),
	CONSTRAINT fk_dh_mach FOREIGN KEY (MaCH) REFERENCES CUA_HANG(MaCH),
	CONSTRAINT fk_dh_magh FOREIGN KEY (MaGH) REFERENCES GIO_HANG(MaGH)
);

CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(30) NOT NULL PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    Tuoi INT NOT NULL,
    GioiTinh NVARCHAR(1) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    MaCH VARCHAR(30) NOT NULL,
	MaQL VARCHAR(30) NOT NULL,
	CONSTRAINT fk_nv_maql FOREIGN KEY (MaQL) REFERENCES NHAN_VIEN(MaNV),
	CONSTRAINT fk_nv_mach FOREIGN KEY (MaCH) REFERENCES CUA_HANG(MaCH)
);


CREATE TABLE TIN_TUC (
    MaTinTuc VARCHAR(30) NOT NULL PRIMARY KEY,
    TieuDe NVARCHAR(200) NOT NULL,
    NoiDung NVARCHAR(500) NOT NULL,
    NgayDang DATETIME NOT NULL,
    HinhAnh NVARCHAR(100),
    MaNV VARCHAR(30) NOT NULL,
	CONSTRAINT fk_tt_manv FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE DANH_GIA(
    MaDG VARCHAR(30) NOT NULL PRIMARY KEY,
    Diem FLOAT NOT NULL,
    NoiDung NVARCHAR(200),
    HinhAnh NVARCHAR(100),
    MaSP VARCHAR(30) NOT NULL,
	MaKH VARCHAR(30) NOT NULL,
	CONSTRAINT fk_dg_masp FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP),
	CONSTRAINT fk_dg_makh FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);
GO